### PR TITLE
Feature meta data

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by acrellin** [comment]
Is this a synthesis of all of our open pull requests? ☺️

**Comment by acrellin** [comment]
Nice! Like the feature category stuff. I'll push on the tags functionality Monday and Tuesday.

**Comment by stefanv** [comment]
Yes, I blended them all together to see how they worked :)  Turns out, pretty well!  I then made sure the docs get generated correctly, etc.  I'm still not quite happy with the documentation for the features---it doesn't quite feel right.  Perhaps you have some ideas on how to improve that.

**Comment by acrellin** [comment]
I'll need more than "doesn't quite feel right" to know how to refactor it
to your liking.

**Comment by acrellin** [comment]
Where are we at on this one?

**Comment by stefanv** [comment]
We're good to go, I think.

**Comment by acrellin** [comment]
Ok, feel free to merge.

**Pull request merged**
