### PR TITLE
Add note regarding MSVC

### PR DESCRIPTION
**Pull request by filmor**
This would have saved me quite a bit of time :)

### CODE REVIEW

**Comment by stefanv** [comment]
This *should* not be true; can you expand on the problem?  We may be able to fix it quite easily.

**Comment by filmor** [comment]
Well, it is :)

The Lomb-Scargle code (e.g. https://github.com/cesium-ml/cesium/blob/master/cesium/features/_lomb_scargle.h#L81, but there are a lot of other places both in `_lomb_scargle.h` and `_eigs.h`) uses Variable Length Arrays which are explicitly not supported by MSVC (see https://stackoverflow.com/questions/5246900) as they are not valid C++.

If someone wanted to clean that up, the correct function to use instead would be https://msdn.microsoft.com/en-us/library/5471dc8s.aspx. Of course, if the size of those arrays could be limited in some way, you could just use staticly sized buffers instead.

**Comment by stefanv** [comment]
I believe you :)

I don't think there's any reason why we can't just allocate some memory here, instead of using the heap.  Are you interested in helping out, or should I take a pass at it?  This is the oldest part of the code base (came from a previous project), and hasn't seen much attention recently I'm afraid.

**Comment by filmor** [comment]
I currently don't have the time to work on this, a note in your README is all I can do right now ;)

If you are looking into this, consider dirching the implementation and instead using only scipy's or gatspy's. You depend on those anyway and this would make your package pure Python.

**Comment by stefanv** [comment]
We've thought about replacing this implementation, but it still offers some features not found in the others.  But we'd certainly be open to that, eventually.

**Pull request merged**
