### PR TITLE
Reorganize `time_series.from_netcdf` to only open file once

### PR DESCRIPTION
**Pull request by bnaul**
Hopefully fixes issue when loading time series on dask.distributed
workers.

### CODE REVIEW

**Comment by stefanv** [comment]
🐽 

Why are all those binary files changed, btw?

**Comment by bnaul** [comment]
Those are test data; I renamed some attribute based on what I mentioned earlier (`name` being protected) and those files needed to be changed accordingly.

**Comment by stefanv** [comment]
Ok, looks good to me.

**Comment by acrellin** [comment]
Looks good

**Pull request merged**
