### PR TITLE
Change "collections" into "collections.abc" for Python 3.10 compatibility

### PR DESCRIPTION
**Pull request by YannCabanes**
For Python 3.10 compatibility, "from collections import Iterable" should be changed into "from collections.abc import Iterable".
See for example:
https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python

### CODE REVIEW

**Comment by stefanv** [comment]
Thank you for the patch. I need to get the limiter running, then we can merge.

**Comment by YannCabanes** [comment]
It seems that the "black" and "flake8" tests have failed.

**Comment by stefanv** [comment]
We may need to pin newer versions of black. Again, I'm happy to do it (but if you can, that'd be great: I'm out on leave for a bit).

**Comment by YannCabanes** [comment]
Now the "flake8" test has passed but the "black" test has failed.

**Comment by stefanv** [comment]
Real close now!

**Comment by YannCabanes** [comment]
The test related to black is still failing.
The default line length of "black" is 88 characters per line. 
However, the maximum line length expected by flake8 in cesium is 80: the file "cesium/.flake8" specifies "max-line-length = 80".
To solve this problem, we can change the maximum value of the line length to 88 expected by flake8: "max-line-length = 88" in the file "cesium/.flake8". 
What do you think about it? Can I do this modification?
Or we could try to enforce black to use the option --line-length=80 during the tests.

**Comment by stefanv** [comment]
We can use the same configuration as used by https://github.com/skyportal/skyportal, which is a bit more flexible wrt line lengths (following the advice given in the black documentation).

**Comment by stefanv** [comment]
Hooray! Thank you @YannCabanes!

**Comment by YannCabanes** [comment]
Hello @stefanv, 
Thanks a lot for merging this pull request. 
Could you release a new version of cesium including this pull request please?
I contribute to a Python package name "tslearn" which develops machine learning algorithms for times series:
https://github.com/tslearn-team/tslearn
The package tslearn imports cesium, so tslearn cannot be compatible with Python 3.10 as long as cesium is not compatible with Python 3.10.

**Comment by stefanv** [comment]
@YannCabanes I have made a release for Python 3.10 compatibility. Now that I have the release process sorted out, it should be easier to do future releases, and we can speed up the inclusion of new features / bugfixes.

**Pull request merged**
