### PR TITLE
Model selection

### PR DESCRIPTION
**Pull request by arkwave**
Updated `sklearn.grid_search` to `sklearn.model_selection` as per #138. Underlying code does not appear to need much changing, but please let me and @alejandrogarciasalas know if this breaks anything.

### CODE REVIEW

**Comment by bnaul** [comment]
This won't work with older versions of `scikit-learn`: an easy way to stay backwards-compatible would be

```
try:
    from sklearn.model_selection import GridSearchCV
except:
    from sklearn.grid_search import GridSearchCV
```

**Comment by arkwave** [comment]
@bnaul sounds good, I'll make that change right away. Do you see anything else that might be problematic?

**Comment by stefanv** [comment]
@bnaul Are you happy with this approach, or would you like to see it refactored into something like ``from sklearn_compat import ...``?

**Comment by bnaul** [comment]
I think this is the right way to do it; adding a new layer just to handle this 1 piece of logic feels too heavy to me. If we run into any other similar issues then it might make sense to combine but for now 👍

**Comment by stefanv** [comment]
Good job, @arkwave & @alejandrogarciasalas

**Pull request merged**
